//! Reader for a resolved dependency version in `Cargo.lock`.
//!
//! Its home is `build.rs`, which includes it by path; a build script has
//! no dependencies of its own to parse TOML with, and the lock file's
//! shape is fixed enough that it does not need one. It lives in a file
//! of its own so that the crate can pull it in under `cfg(test)` as
//! well, because cargo runs no tests in a build script.

/// The `version` of the `[[package]]` stanza naming `crate_name`.
///
/// The first `version` after the matching `name`, so a name appearing
/// anywhere else in the stanza — in a `dependencies` list, say, where it
/// is a bare quoted string rather than a `name = ` field — is not a
/// match, and a crate locked at two versions answers with the first.
pub fn locked_version<'a>(lock: &'a str, crate_name: &str) -> Option<&'a str> {
    let name = format!("name = \"{crate_name}\"");
    let mut named = false;
    for line in lock.lines().map(str::trim) {
        if line == "[[package]]" {
            named = false;
        } else if line == name {
            named = true;
        } else if named
            && let Some(version) = line
                .strip_prefix("version = \"")
                .and_then(|rest| rest.strip_suffix('"'))
        {
            return Some(version);
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::locked_version;

    /// The header, two stanzas whose names share a prefix, and a crate
    /// locked at two versions: the whole shape the real lock file has.
    const LOCK: &str = r#"
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "css-to-xpath"
version = "0.3.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "phf",
 "selectors",
]

[[package]]
name = "phf"
version = "0.13.1"

[[package]]
name = "phf_shared"
version = "0.12.0"

[[package]]
name = "syn"
version = "2.0.119"

[[package]]
name = "syn"
version = "3.0.2"
"#;

    #[test]
    fn reads_the_version_of_a_named_package() {
        assert_eq!(locked_version(LOCK, "css-to-xpath"), Some("0.3.0"));
    }

    #[test]
    fn does_not_match_a_name_a_longer_name_starts_with() {
        assert_eq!(locked_version(LOCK, "phf"), Some("0.13.1"));
        assert_eq!(locked_version(LOCK, "phf_shared"), Some("0.12.0"));
    }

    #[test]
    fn takes_the_first_of_a_package_locked_twice() {
        assert_eq!(locked_version(LOCK, "syn"), Some("2.0.119"));
    }

    #[test]
    fn ignores_a_name_that_is_only_a_dependency_entry() {
        // `selectors` is listed as a dependency of css-to-xpath and has
        // no stanza of its own, so the lock does not know its version —
        // the header's `version = 4` must not be offered instead.
        assert_eq!(locked_version(LOCK, "selectors"), None);
    }

    #[test]
    fn is_none_for_a_package_the_lock_does_not_have() {
        assert_eq!(locked_version(LOCK, "serde"), None);
    }
}
