# Generated by savvy: do not edit by hand
#
# Note:
#   This wrapper file is named as `000-wrappers.R` so that this file is loaded
#   first, which allows users to override the functions defined here (e.g., a
#   print() method for an enum).

#' @useDynLib selectrs, .registration = TRUE
#' @keywords internal
NULL

# Check class and extract the external pointer embedded in the environment
.savvy_extract_ptr <- function(e, class) {
  if(is.null(e)) {
    return(NULL)
  }

  if(inherits(e, class)) {
    e$.ptr
  } else {
    msg <- paste0("Expected ", class, ", got ", class(e)[1])
    stop(msg, call. = FALSE)
  }
}

# Prohibit modifying environments

#' @export
`$<-.savvy_selectrs__sealed` <- function(x, name, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' @export
`[[<-.savvy_selectrs__sealed` <- function(x, i, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' Translate CSS selectors to XPath expressions
#'
#' The vectorized core of `css_to_xpath()`. R has already validated and
#' recycled the arguments to equal length.
#'
#' A selector that fails to translate does not raise an error here: the
#' first failure is returned as the named list `describe_failure()`
#' builds, so that R can raise a condition classed by the kind of
#' failure. Success returns a character vector, so the caller tells the
#' two apart by type.
#'
#' @param selectors A character vector of CSS selectors.
#' @param prefixes A character vector of XPath prefixes.
#' @param translators A character vector: "generic", "html", or "xhtml".
#' @returns A character vector of XPath expressions, or a named list
#'   describing the first selector that could not be translated.
#' @noRd
`css_to_xpath_rust` <- function(`selectors`, `prefixes`, `translators`) {
  .Call(savvy_css_to_xpath_rust__impl, `selectors`, `prefixes`, `translators`)
}

#' Version of the selectrs Rust core
#'
#' Returns the version of the underlying Rust crate. A trivial export used
#' to verify that the Rust toolchain and FFI bindings are working.
#'
#' @returns A length-one character vector.
#' @noRd
`selectrs_core_version` <- function() {
  .Call(savvy_selectrs_core_version__impl)
}


